### 3.3 변수, 연산, 자료형
####3.3.1 변수와 연산
프로그램에는 데이터를 보관하는 저장소가 필요한데 데이터를 보관하는 곳을 변수라고 합니다. C언어와 같은 다른 프로그램과 달리 파이썬은 변수에 담는 데이터의 형태 (정수, 부동소수, 문자 등)에 따라 변수 선언을 다르게 할 필요가 없습니다.

In [2]:
value = 2021  # 숫자
# 이것은 주석입니다.  
name = 'Hi'   # 문자
print(value)
print(name) 

2021
Hi


가장 기본적인 연산은 사칙연산입니다. (+,-,*,/)
그 외에 자주 사용되는 연산 기호는 다음과 같습니다. 
- ** : 제곱 (ex) 2 ** 4 -> 16
- // : 정수로 나누었을 때의 몫
- % : 정수로 나누었을 때의 나머지
아래 결과를 확인해보길 바랍니다.

In [3]:
a = 12
b = 5

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a ** b)
print(a % b)

17
7
60
2.4
2
248832
2


#### 3.3.2 자료형
자료형이란 데이터의 형태를 말합니다. 1151과 같은 정수, 3.141592와 같은 실수, 'Hi'와 같은 문자열 등 우리가 프로그래밍에 사용하는 데이터의 형태는 다양합니다. 파이썬의 주요 자료형은 다음과 같습니다. 
숫자의 종류에는 정수형과 실수형이 있습니다. 파이썬에서는 상관없이 변수에 넣어주면 됩니다.
1.5e4 같은 경우에는 컴퓨터의 지수 표현 방식으로 1.5*10^4 를 나타냅니다. 



In [4]:
a = -1.124
b = 1.5e4
c = 1.5e-4
print(a,b,c)

-1.124 15000.0 0.00015


**문자열**

문자열은 문자 데이터를 쭉 나열한 자료형입니다.
문자를 ""(큰따옴표) 또는 ''(작은따옴표)로 둘러쌓으면 됩니다. 
여러 줄을 하나의 변수에 대입하고 싶으면 \n 기호를 줄바꿈 위치에 삽입하면 가능합니다.  

문자열 간에 더하기(+) 연산자를 사용하면 바로 연결 됩니다.

곱하기(*) 연산자를 사용하면 문자열이 반복 됩니다.

문자열에 포함된 문자가 몇 개인지 알고 싶을 때는 len(변수명)을 사용하면 됩니다. 

In [5]:
word = 'python is fun'
print(word)

python is fun


In [6]:
# 문자열 연결하기 (Concatenation)
a = 'my name'
b = 'is'
c = ' Tan'
a + b + c

'my nameis Tan'

In [7]:
# 문자열 곱하기
c*2

' Tan Tan'

In [8]:
# 문자열 길이 구하기
len(a+b+c)

13

문자열 인덱싱과 슬라이싱

인덱싱(Indexing)이란 어떤 것을 뽑아낸다는 의미이고, 슬라이싱(Slicing)은 잘라낸다는 의미입니다.

문자열은 첫 번째 자리부터 0,1,2,3,4 ... 번째로 번호를 매길 수 있습니다. 공백을 포함하며 a[0]는 a라는 문자열의 0번째 문자를 나타냅니다. 

아래 예제에서 0번째 문자는 m입니다. a[-3]은 뒤에서 3번째 문자를 가리키며 'T'입니다. 

문자열 슬라이싱은 여러 개의 문자를 뽑아내고 싶을 때 사용하면 됩니다. a[3:7]은 3,4,5,6 번째 문자를 나타냅니다. 앞 번호를 생략하면 처음부터, 뒷 번호를 생략하면 끝까지 뽑아냅니다. 

In [9]:
# 문자열 인덱싱과 슬라이싱
a = 'my name is Tan'
print(a[4])
print(a[-3])
print(a[3:7])
print(a[4:])
print(a[:5])

a
T
name
ame is Tan
my na


**리스트 (List)**

리스트를 사용하면 여러 모음을 하나의 변수로 저장할 수 있습니다. 

리스트명 = [요소1, 요소2, 요소3, 요소4, ...] 

이렇게 만들어주면 하나의 리스트에 여러 요소들이 담기게 됩니다. 앞에서 배운 숫자, 문자열이 요소가 될 수 있고 리스트도 리스트의 요소가 될 수 있습니다. 


In [10]:
# 빈 리스트 
a = []
# 문자열 리스트
b = ['python', 'is', 'fun']

# 숫자와 문자열 리스트
c = [1, 2, 3, 5, 8, 'fibonnaci']
# 리스트 c를 요소로 갖는 리스트
d = ['list', c]
print(a, b, c)
print(d)

[] ['python', 'is', 'fun'] [1, 2, 3, 5, 8, 'fibonnaci']
['list', [1, 2, 3, 5, 8, 'fibonnaci']]


앞서 문자열과 같이 리스트도 인덱싱을 할 수 있습니다. A=[1, 3, 5, 7, ['odd', 'numers']]인 리스트 A가 있으면, A[0]는 0번째 요소인 1을 나타냅니다.
리스트 요소 중 A[4]는 ['odd', 'numbers']가 되는데 여기서 첫 번째 요소를 가져오고 싶으면 A[4][0]으로 표현하면 됩니다.

In [11]:
a = [1, 3, 5, 7, ['odd','numbers']]
print(a[0])
print(a[4])
print(a[4][1])

1
['odd', 'numbers']
numbers


리스트에는 리스트를 편하게 가공하기 위해 다양한 내장 함수를 제공합니다. 

In [12]:
a = [1, 3, 5, 7, 100, 100.5, 941.2, 18.51]

# 리스트의 길이 구하기
print(len(a))
# 리스트의 min, max
print(min(a))
print(max(a))
# 리스트의 합
print(sum(a))
# 오름차순 정렬
print(sorted(a))

b = [1, 2, 3, 4]
name = ['Sugar', 'JHO', 'Mina', 'Yeji', 'Mina']
# 리스트 요소 삭제
del b[1]
print(b)
# 리스트 요소 추가
b.append(5)
print(b)
# 리스트 요소 삽입
b.insert(1,2.5)
print(b)
# 리스트에 여러 요소 삽입
b.extend([6, 7, 8, 9])
print(b)
# 리스트 순서 뒤집기
name.reverse()
print(name)
# 요소가 저장된 인덱스 반환
print(name.index('Mina'))
# 요소의 개수 반환 
print(name.count('Mina'))


8
1
941.2
1176.21
[1, 3, 5, 7, 18.51, 100, 100.5, 941.2]
[1, 3, 4]
[1, 3, 4, 5]
[1, 2.5, 3, 4, 5]
[1, 2.5, 3, 4, 5, 6, 7, 8, 9]
['Mina', 'Yeji', 'Mina', 'JHO', 'Sugar']
0
2


**튜플 (Tuple)**

튜플은 리스트와 거의 비슷하지만 다음 두 가지가 다릅니다.

1) 리스트는 []를 사용하지만 튜플은 ()를 사용한다. 

2) 리스트는 요소들을 생성, 삭제, 수정 할 수 있지만 튜플은 요소 값들을 바꿀 수 없다. 

따라서, 값이 항상 변하지 않는 것을 원할 때 튜플에 값을 저장하면 됩니다. 

인덱싱과 슬라이싱은 리스트와 동일하게 할 수 있습니다. 


In [13]:
a = ()
b = (1,)
c = (1, 2, 3)
d = 1, 2, 3
e = ('a', 'b', ('ab', 'cd'))
print(e[1:])
print(len(e))

('b', ('ab', 'cd'))
3


**딕셔너리 (Dictionary)**

딕셔너리는 Key와 Value로 이루어진 자료형입니다. 예를 들어 사람은 '이름', '나이','취미' 라는 Key 값을 갖고 이에 대응되는 '이지은', '15', '노래' 값을 가질 수 있습니다. 이런 식으로 대응 관계가 포함된 배열을 저장할 때 딕셔너리를 사용하면 됩니다. 

{Key1:Value1, Key2:Value2, Key3:Value3, ...}


In [14]:
dic = {'name':'IU', 'age':15, 'hobby':'sing'}
dic

{'age': 15, 'hobby': 'sing', 'name': 'IU'}

여기에 추가적으로 'height'라는 Key와 Value 쌍을 추가하고 싶다면

In [15]:
dic['height'] = 160
dic

{'age': 15, 'height': 160, 'hobby': 'sing', 'name': 'IU'}

딕셔너리는 이렇게 어떤 쌍을 이루는 데이터를 저장할 때 매우 유용합니다. 예를 들어, 네 사람의 점수를 저장하고 싶다면

score = {'IU':90, 'sugar':80, 'sana':75, 'winter':85}

이렇게 저장할 수 있습니다. 특정 key의 value를 알고 싶다면 score[key] 처럼 사용하면 됩니다. 

In [16]:
score = {'IU':90, 'sugar':80, 'sana':75, 'winter':85}
print(score['IU'])
print(score['winter'])

90
85


딕셔너리 키:요소 추가
딕셔너리 요소 제거 


In [17]:
# key 뽑아내기
score.keys()
print(score.keys())
# value 뽑아내기
score.values()
print(score.values())
# key로 value 뽑아내기
a = score.get('rm')
print(a)

dict_keys(['IU', 'sugar', 'sana', 'winter'])
dict_values([90, 80, 75, 85])
None


**넘파이(Numpy)**

Numpy는 행렬을 이용하여 수치 데이터를 다룰 때 매우 자주 사용되는 파이썬 패키지입니다. 


In [18]:
import numpy as np

Numpy의 주요 모듈
1. np.array()  : 리스트, 튜플, 배열로 부터 ndarray를 생성
2. np.asarray(): 기존의 array로 부터 ndarray를 생성
3. np.arange() : range와 비슷
4. np.linspace(start, end, num) : [start, end] 균일한 간격으로 num개 생성
5. np.logspace(start, end, num) : [start, end] log scale 간격으로 num개 생성

In [19]:
a = np.array([1, 2, 3, 4, 5]) #리스트를 가지고 1차원 배열 생성
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [20]:
b = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(b)

[[10 20 30]
 [60 70 80]]


In [21]:
print(b.ndim)   # 몇 차원 행렬?
print(b.shape)  # 어떤 모양의 행렬?

2
(2, 3)


list로 부터 ndarray 생성

In [22]:
c = [1, 2, 3, 4]
n_c = np.array(c)
print(c, n_c)

[1, 2, 3, 4] [1 2 3 4]




```
# 코드로 형식 지정됨
```

arange()와 reshape()

In [23]:
# arange로 0~29 숫자 생성 후 reshape 
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Numpy 슬라이싱

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
b=a[0:2, 0:2]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
